# Generated by Django 5.2 on 2025-04-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magic', '0003_remove_project_organization_remove_progress_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='polygon_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
