# Generated by Django 5.2 on 2025-04-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magic', '0004_project_polygon_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='boundary',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tahsil',
            name='boundary',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='boundary',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
